name: CI

on:
  push:
    branches:
      - main
      - levels/4
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: pnpm install && cd server && pnpm install && cd .. && cd e2e && pnpm install

      - name: Run unit tests
        run: npm test

  e2e: 
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: pnpm/action@v4

    - name: Start app
      run: pnpm install && nohup pnpm start
    - name: Install server dependencies
      run: cd server && pnpm install && nohup pnpm start
    - name: Run e2e tests
      run: cd e2e && pnpm install && pnpm cypress run 

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist